- name: Create the logging file
  template:
    src: openstack-logs.j2
    dest: /etc/rsyslog.d/22-openstack-logs.conf
    owner: "syslog"
    group: "adm"
    mode: "0644"

- name: Create the Operating System logging file
  template:
    src: os-logs.j2
    dest: /etc/rsyslog.d/24-os-logs.conf
    owner: "syslog"
    group: "adm"
    mode: "0644"
